version: "3.9"

services:
  telegram-bot:
    image: telegram-bot
    env_file:
      - ./.env
    volumes:
      - .:/app
    networks:
      - minecraft-net

networks:
  minecraft-net:
    external: true